version: "3.8"
services:

  config-service:
    container_name: config-server
    build:
      context: ./efms_config
      dockerfile: Dockerfile
    image: config-service:config-service-1.0.0
    ports:
      - "8888:8888"
#    environment:
#      SPRING_PROFILES_ACTIVE: prod
    networks:
      micro_network:
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

  discovery-service:
    container_name: discovery-server
    build:
      context: ./efms_discovery
      dockerfile: Dockerfile
    image: discovery-service:discovery-service-1.0.0
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: prod

    depends_on:
      - config-service
    networks:
      micro_network:
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

  gateway-service:
    container_name: gateway-server
    build:
      context: ./efms_gateway
      dockerfile: Dockerfile
    image: gateway-service:gateway-service-1.0.0
    ports:
      - "8765:8765"
    environment:
      SPRING_PROFILES_ACTIVE: prod

    depends_on:
      - config-service
    networks:
      micro_network:
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

  core-service:
    container_name: core-server
    build:
      context: ./efms_core
      dockerfile: Dockerfile
    image: core-service:core-service-1.0.0
    ports:
      - "8084:8084"
    environment:
#      SPRING_CLOUD_CONFIG_URI: http://config-service:8888
#      SPRING_PROFILES_ACTIVE: dev
      SPRING_PROFILES_ACTIVE: prod

    depends_on:
      - config-service
    networks:
      micro_network:
    deploy:
      resources:
        limits:
          memory: 512M

  auth-service:
    container_name: auth-server
    build:
      context: ./efms_auth
      dockerfile: Dockerfile
    image: auth-service:auth-service-1.0.0
    ports:
      - "8085:8085"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - config-service
    networks:
      micro_network:
    deploy:
      resources:
        limits:
          memory: 512M

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      micro_network:

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      micro_network:

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      micro_network:

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:8.11.0
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ../monitoring/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      - "LS_JAVA_OPTS=-Xmx512m -Xms512m"
    depends_on:
      - elasticsearch
    networks:
      micro_network:

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.11.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      micro_network:

volumes:
  grafana-data:
  elasticsearch-data:

networks:
  micro_network:
    driver: bridge
