spring:
  application:
    name: fms_gateway
  profiles:
    active: dev
  cloud:
    config:
      profile: dev
      enabled: true
  config:
    import: optional:configserver:http://localhost:8888

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
