/**
 * ALL RIGHT RESERVED By kavinda_d
 *
 * @AUTHOR : kavinda_d
 * @PROJECT : fms backend
 */
package net.com.fms_core.util.mapping;
import java.util.*;

public class IsoFieldDropdownMapper {
    public static List<Map<String, String>> getIsoFieldOptions() {
        List<Map<String, String>> options = new ArrayList<>();
        addOption(options, "MESSAGE TYPE INDICATOR", "messageTypeIndicator");
        addOption(options, "BIT MAP", "bitMap");
        addOption(options, "PAN", "pan");
        addOption(options, "PROCESSING CODE", "processingCode");
        addOption(options, "AMOUNT, TRANSACTION", "amount");
        addOption(options, "AMOUNT, SETTLEMENT", "settlementAmount");
        addOption(options, "AMOUNT, CARDHOLDER BILLING", "cardholderBillingAmount");
        addOption(options, "TRANSACTION DATE AND TIME", "transactionDateTime");
        addOption(options, "AMOUNT, CARDHOLDER BILLING FEE", "cardholderBillingFeeAmount");
        addOption(options, "CONVERSION RATE, SETTLEMENT", "settlementConversionRate");
        addOption(options, "CONVERSION RATE, CARDHOLDER BILLING", "cardholderBillingConversionRate");
        addOption(options, "STAN", "stan");
        addOption(options, "LOCAL TRANSACTION TIME", "localTransactionTime");
        addOption(options, "LOCAL TRANSACTION DATE", "localTransactionDate");
        addOption(options, "EXPIRY DATE", "expiryDate");
        addOption(options, "SETTLEMENT DATE", "settlementDate");
        addOption(options, "CONVERSION DATE", "conversionDate");
        addOption(options, "CAPTURE DATE", "captureDate");
        addOption(options, "MERCHANT TYPE(MCC)", "merchantCategoryCode");
        addOption(options, "ACQUIRING INSTITUTION COUNTRY CODE", "acquiringCountryCode");
        addOption(options, "PAN EXTENDED COUNTRY CODE", "panExtendedCountryCode");
        addOption(options, "FORWARDING INSTITUTION COUNTRY CODE", "forwardingCountryCode");
        addOption(options, "POS ENTRY MODE", "posEntryMode");
        addOption(options, "CARD SEQUENCE NUMBER", "cardSequenceNumber");
        addOption(options, "NETWORK INTERNATIONAL IDENTIFIEER", "networkId");
        addOption(options, "POINT OF SERVICE CONDITION CODE", "posConditionCode");
        addOption(options, "POINT OF SERVICE PIN CAPTURE CODE", "posPinCaptureCode");
        addOption(options, "AUTHORIZATION IDENTIFICATION RESP LEN", "authResponseLength");
        addOption(options, "TRANSACTION FEE AMOUNT", "transactionFeeAmount");
        addOption(options, "SETTLEMENT FEE AMOUNT", "settlementFeeAmount");
        addOption(options, "TRANSACTION PROCESSING FEE AMOUNT", "transactionProcessingFee");
        addOption(options, "SETTLEMENT PROCESSING FEE AMOUNT", "settlementProcessingFee");
        addOption(options, "ACQUIRER INST ID CODE", "acquirerInstitutionId");
        addOption(options, "FORWARDING INST ID CODE", "forwardingInstitutionId");
        addOption(options, "PAN EXTENDED", "panExtended");
        addOption(options, "TRACK 2 DATA", "track2Data");
        addOption(options, "TRACK 3 DATA", "track3Data");
        addOption(options, "RETRIEVAL REFERENCE NUMBER", "retrievalReferenceNumber");
        addOption(options, "AUTH RESPONSE", "authResponse");
        addOption(options, "RESPONSE CODE", "responseCode");
        addOption(options, "SERVICE RESTRICTION CODE", "serviceRestrictionCode");
        addOption(options, "CARD ACCEPTOR TERMINAL IDENTIFICATION", "terminalId");
        addOption(options, "CARD ACCEPTOR ID CODE", "cardAcceptorId");
        addOption(options, "CARD ACCEPTOR NAME,LOCATION", "cardAcceptorNameLocation");
        addOption(options, "ADDITIONAL RESPONSE DATA", "additionalResponseData");
        addOption(options, "TRACK 1 DATA", "track1Data");
        addOption(options, "ADDITIONAL DATA - ISO", "additionalDataIso");
        addOption(options, "ADDITIONAL DATA - NATIONAL", "additionalDataNational");
        addOption(options, "ADDITIONAL DATA - PRIVATE", "additionalDataPrivate");
        addOption(options, "TRANSACTION CURRENCY CODE", "transactionCurrencyCode");
        addOption(options, "CURRENCY CODE, SETTLEMENT", "settlementCurrencyCode");
        addOption(options, "CARDHOLDER BILLING CURRENCY CODE", "cardholderBillingCurrencyCode");
        addOption(options, "PIN DATA", "pinData");
        addOption(options, "SECURITY RELATED CONTROL INFORMATION", "securityControlInfo");
        addOption(options, "BALANCE INFORMATION", "balanceInformation");
        addOption(options, "RESERVED ISO", "reservedIso55");
        addOption(options, "RESERVED ISO", "reservedIso56");
        addOption(options, "RESERVED NATIONAL", "reservedNational57");
        addOption(options, "RESERVED NATIONAL", "reservedNational58");
        addOption(options, "NATIONAL POS GEOGRAPHIC DATA", "nationalPosGeographicData");
        addOption(options, "RESERVED PRIVATE", "reservedPrivate60");
        addOption(options, "RESERVED PRIVATE", "reservedPrivate61");
        addOption(options, "FIELD 62", "field62");
        addOption(options, "SMS PRIVATE-USE FIELDS", "smsPrivateFields");
        addOption(options, "MESSAGE AUTHENTICATION CODE FIELD", "macField");
        addOption(options, "BITMAP, EXTENDED", "extendedBitMap");
        addOption(options, "SETTLEMENT CODE", "settlementCode");
        addOption(options, "EXTENDED PAYMENT CODE", "extendedPaymentCode");
        addOption(options, "RECEIVING INSTITUTION COUNTRY CODE", "receivingInstitutionCountryCode");
        addOption(options, "SETTLEMENT INSTITUTION COUNTRY CODE", "settlementInstitutionCountryCode");
        addOption(options, "NETWORK MANAGEMENT INFORMATION CODE", "networkManagementCode");
        addOption(options, "MESSAGE NUMBER", "messageNumber");
        addOption(options, "MESSAGE NUMBER LAST", "messageNumberLast");
        addOption(options, "DATE ACTION", "dateAction");
        addOption(options, "CREDITS NUMBER", "creditsNumber");
        addOption(options, "CREDITS REVERSAL NUMBER", "creditsReversalNumber");
        addOption(options, "DEBITS NUMBER", "debitsNumber");
        addOption(options, "DEBITS REVERSAL NUMBER", "debitsReversalNumber");
        addOption(options, "TRANSFER NUMBER", "transferNumber");
        addOption(options, "TRANSFER REVERSAL NUMBER", "transferReversalNumber");
        addOption(options, "INQUIRIES NUMBER", "inquiriesNumber");
        addOption(options, "AUTHORIZATION NUMBER", "authorizationNumber");
        addOption(options, "CREDITS, PROCESSING FEE AMOUNT", "creditsProcessingFee");
        addOption(options, "CREDITS, TRANSACTION FEE AMOUNT", "creditsTransactionFee");
        addOption(options, "DEBITS, PROCESSING FEE AMOUNT", "debitsProcessingFee");
        addOption(options, "DEBITS, TRANSACTION FEE AMOUNT", "debitsTransactionFee");
        addOption(options, "CREDITS, AMOUNT", "creditsAmount");
        addOption(options, "CREDITS, REVERSAL AMOUNT", "creditsReversalAmount");
        addOption(options, "DEBITS, AMOUNT", "debitsAmount");
        addOption(options, "DEBITS, REVERSAL AMOUNT", "debitsReversalAmount");
        addOption(options, "ORIGINAL DATA ELEMENTS", "originalDataElements");
        addOption(options, "FILE UPDATE CODE", "fileUpdateCode");
        addOption(options, "FILE SECURITY CODE", "fileSecurityCode");
        addOption(options, "RESPONSE INDICATOR", "responseIndicator");
        addOption(options, "SERVICE INDICATOR", "serviceIndicator");
        addOption(options, "ADDITIONAL RESPONSE DATA", "field95");
        addOption(options, "MESSAGE SECURITY CODE", "messageSecurityCode");
        addOption(options, "AMOUNT, NET SETTLEMENT", "netSettlementAmount");
        addOption(options, "PAYEE", "payee");
        addOption(options, "SETTLEMENT INSTITUTION IDENT CODE", "settlementInstitutionId");
        addOption(options, "RECEIVING INSTITUTION IDENT CODE", "receivingInstitutionId");
        addOption(options, "FILE NAME", "fileName");
        addOption(options, "ACCOUNT IDENTIFICATION 1", "accountIdentification1");
        addOption(options, "ACCOUNT IDENTIFICATION 2", "accountIdentification2");
        addOption(options, "TRANSACTION DESCRIPTION", "transactionDescription");
        addOption(options, "RESERVED ISO USE 105", "reservedIso105");
        addOption(options, "RESERVED ISO USE 106", "reservedIso106");
        addOption(options, "RESERVED ISO USE 107", "reservedIso107");
        addOption(options, "RESERVED ISO USE 108", "reservedIso108");
        addOption(options, "RESERVED ISO USE 109", "reservedIso109");
        addOption(options, "RESERVED ISO USE 110", "reservedIso110");
        addOption(options, "RESERVED ISO USE 111", "reservedIso111");
        addOption(options, "RESERVED NATIONAL USE 112", "reservedNational112");
        addOption(options, "RESERVED NATIONAL USE 113", "reservedNational113");
        addOption(options, "RESERVED NATIONAL USE 114", "reservedNational114");
        addOption(options, "ADDITIONAL TRACE DATA 1", "reservedNational115");
        addOption(options, "RESERVED NATIONAL USE 116", "reservedNational116");
        addOption(options, "RESERVED NATIONAL USE 117", "reservedNational117");
        addOption(options, "INTRA-COUNTRY DATA", "reservedNational118");
        addOption(options, "RESERVED NATIONAL USE", "reservedNational119");
        addOption(options, "RESERVED PRIVATE USE", "reservedPrivate120");
        addOption(options, "ISSUING INSTITUTION IDENT CODE", "issuingInstitutuinIdentCode");
        addOption(options, "REMAINING OPEN-TO-USE", "remainingOpenToUse");
        addOption(options, "ADDRESS VERIFICATION DATA", "addressVerificationResult");
        addOption(options, "FREE-FORM TEXT-JAPAN", "freeFormTextJapan");
        addOption(options, "SUPPORTING INFORMATION", "supportingInformation");
        addOption(options, "FIELD 126", "field126");
        addOption(options, "MAC 2", "mac2");
        return options;
    }
    private static void addOption(List<Map<String, String>> list, String label, String value) {
        Map<String, String> option = new HashMap<>();
        option.put("name", label);
        option.put("value", value);
        list.add(option);
    }
}
