package net.com.fms_core.service.impl;

import lombok.extern.slf4j.Slf4j;
import net.com.fms_core.dto.AIRuleTestResultDTO;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

@Service
@Slf4j
public class AIRulePDFReportService {

    public byte[] generateComprehensiveTextReport(List<AIRuleTestResultDTO> testResults, 
                                                String ruleGroupName, 
                                                LocalDateTime startDate, 
                                                LocalDateTime endDate) throws IOException {
        
        try {
            String reportContent = generateReportContent(testResults, ruleGroupName, startDate, endDate);
            return reportContent.getBytes("UTF-8");
            
        } catch (Exception e) {
            log.error("Error generating text report", e);
            throw new IOException("Failed to generate text report", e);
        }
    }
    
    private String generateReportContent(List<AIRuleTestResultDTO> testResults, 
                                       String ruleGroupName, 
                                       LocalDateTime startDate, 
                                       LocalDateTime endDate) {
        
        StringBuilder report = new StringBuilder();
        
        // Title and Header
        report.append("=".repeat(80)).append("\n");
        report.append("                    AI RULE TESTING & VALIDATION REPORT\n");
        report.append("                   COMPREHENSIVE FRAUD ANALYSIS SYSTEM\n");
        report.append("=".repeat(80)).append("\n\n");
        
        // Report Details
        report.append("REPORT DETAILS\n");
        report.append("-".repeat(40)).append("\n");
        report.append("Rule Group: ").append(ruleGroupName).append("\n");
        report.append("Test Period: ").append(startDate.format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm")))
              .append(" to ").append(endDate.format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm"))).append("\n");
        report.append("Report Generated: ").append(LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"))).append("\n");
        report.append("Total Transactions: ").append(testResults.size()).append("\n\n");
        
        // Executive Summary
        addExecutiveSummary(report, testResults);
        
        // Transaction Analysis
        addTransactionAnalysis(report, testResults);
        
        // Risk Analysis
        addRiskAnalysis(report, testResults);
        
        // Model Performance
        addModelPerformance(report, testResults);
        
        // Recommendations
        addRecommendations(report, testResults);
        
        // Report Footer
        report.append("=".repeat(80)).append("\n");
        report.append("Report generated by FMS AI Rule Testing System\n");
        report.append("For technical support, contact the FMS development team\n");
        report.append("=".repeat(80)).append("\n");
        
        return report.toString();
    }
    
    private void addExecutiveSummary(StringBuilder report, List<AIRuleTestResultDTO> testResults) {
        report.append("EXECUTIVE SUMMARY\n");
        report.append("-".repeat(40)).append("\n");
        
        long totalTransactions = testResults.size();
        long flaggedTransactions = testResults.stream()
            .filter(result -> result.getDetails() != null && 
                    result.getDetails().getFraudPercentage() != null && 
                    result.getDetails().getFraudPercentage() > 0.5)
            .count();
        
        double flaggedPercentage = totalTransactions > 0 ? (flaggedTransactions * 100.0) / totalTransactions : 0;
        
        report.append("Total Transactions Tested: ").append(totalTransactions).append("\n");
        report.append("Flagged Transactions: ").append(flaggedTransactions).append("\n");
        report.append("Flag Rate: ").append(String.format("%.2f%%", flaggedPercentage)).append("\n");
        
        // Risk Distribution
        Map<String, Long> riskDistribution = testResults.stream()
            .collect(Collectors.groupingBy(
                result -> {
                    if (result.getDetails() == null || result.getDetails().getRiskScore() == null) return "Unknown";
                    double risk = result.getDetails().getRiskScore();
                    if (risk >= 80) return "High Risk";
                    else if (risk >= 50) return "Medium Risk";
                    else return "Low Risk";
                },
                Collectors.counting()
            ));
        
        report.append("\nRisk Distribution:\n");
        for (Map.Entry<String, Long> entry : riskDistribution.entrySet()) {
            report.append("  ").append(entry.getKey()).append(": ").append(entry.getValue()).append("\n");
        }
        report.append("\n");
    }
    
    private void addTransactionAnalysis(StringBuilder report, List<AIRuleTestResultDTO> testResults) {
        report.append("TRANSACTION ANALYSIS\n");
        report.append("-".repeat(40)).append("\n");
        
        // Show first 10 transactions as sample
        List<AIRuleTestResultDTO> sampleTransactions = testResults.stream()
            .limit(10)
            .collect(Collectors.toList());
        
        report.append("Sample Transactions (First 10):\n");
        report.append(String.format("%-15s %-12s %-20s %-10s %-12s %-15s\n", 
            "Transaction ID", "Amount", "PAN", "Risk Score", "Fraud %", "Status"));
        report.append("-".repeat(90)).append("\n");
        
        for (AIRuleTestResultDTO result : sampleTransactions) {
            String riskScore = "N/A";
            String fraudPercentage = "N/A";
            
            if (result.getDetails() != null) {
                if (result.getDetails().getRiskScore() != null) {
                    riskScore = String.format("%.1f", result.getDetails().getRiskScore());
                }
                if (result.getDetails().getFraudPercentage() != null) {
                    fraudPercentage = String.format("%.3f", result.getDetails().getFraudPercentage());
                }
            }
            
            report.append(String.format("%-15s %-12s %-20s %-10s %-12s %-15s\n",
                result.getTransactionId() != null ? result.getTransactionId().toString() : "N/A",
                result.getAmount() != null ? String.format("%.2f", result.getAmount()) : "N/A",
                result.getPan() != null ? 
                    (result.getPan().length() > 18 ? result.getPan().substring(0, 18) + ".." : result.getPan()) : "N/A",
                riskScore,
                fraudPercentage,
                result.getStatus() != null ? result.getStatus() : "N/A"));
        }
        
        if (testResults.size() > 10) {
            report.append("\n... and ").append(testResults.size() - 10).append(" more transactions\n");
        }
        report.append("\n");
    }
    
    private void addRiskAnalysis(StringBuilder report, List<AIRuleTestResultDTO> testResults) {
        report.append("RISK ANALYSIS\n");
        report.append("-".repeat(40)).append("\n");
        
        // Risk Score Distribution
        Map<String, Long> riskScoreRanges = testResults.stream()
            .filter(result -> result.getDetails() != null && result.getDetails().getRiskScore() != null)
            .collect(Collectors.groupingBy(
                result -> {
                    double risk = result.getDetails().getRiskScore();
                    if (risk >= 90) return "90-100 (Critical)";
                    else if (risk >= 80) return "80-89 (High)";
                    else if (risk >= 60) return "60-79 (Medium-High)";
                    else if (risk >= 40) return "40-59 (Medium)";
                    else if (risk >= 20) return "20-39 (Low-Medium)";
                    else return "0-19 (Low)";
                },
                Collectors.counting()
            ));
        
        report.append("Risk Score Distribution:\n");
        for (Map.Entry<String, Long> entry : riskScoreRanges.entrySet()) {
            report.append("  ").append(entry.getKey()).append(": ").append(entry.getValue()).append("\n");
        }
        
        // Fraud Probability Distribution
        Map<String, Long> fraudPercentageRanges = testResults.stream()
            .filter(result -> result.getDetails() != null && result.getDetails().getFraudPercentage() != null)
            .collect(Collectors.groupingBy(
                result -> {
                    double fraud = result.getDetails().getFraudPercentage();
                    if (fraud >= 0.9) return "90-100% (Very High)";
                    else if (fraud >= 0.7) return "70-89% (High)";
                    else if (fraud >= 0.5) return "50-69% (Medium-High)";
                    else if (fraud >= 0.3) return "30-49% (Medium)";
                    else if (fraud >= 0.1) return "10-29% (Low)";
                    else return "0-9% (Very Low)";
                },
                Collectors.counting()
            ));
        
        report.append("\nFraud Probability Distribution:\n");
        for (Map.Entry<String, Long> entry : fraudPercentageRanges.entrySet()) {
            report.append("  ").append(entry.getKey()).append(": ").append(entry.getValue()).append("\n");
        }
        report.append("\n");
    }
    
    private void addModelPerformance(StringBuilder report, List<AIRuleTestResultDTO> testResults) {
        report.append("MODEL PERFORMANCE\n");
        report.append("-".repeat(40)).append("\n");
        
        long totalTransactions = testResults.size();
        long flaggedTransactions = testResults.stream()
            .filter(result -> result.getDetails() != null && 
                    result.getDetails().getFraudPercentage() != null && 
                    result.getDetails().getFraudPercentage() > 0.5)
            .count();
        
        double detectionRate = totalTransactions > 0 ? (flaggedTransactions * 100.0) / totalTransactions : 0;
        
        double avgRiskScore = testResults.stream()
            .filter(result -> result.getDetails() != null && result.getDetails().getRiskScore() != null)
            .mapToDouble(result -> result.getDetails().getRiskScore())
            .average()
            .orElse(0.0);
        
        double avgFraudProb = testResults.stream()
            .filter(result -> result.getDetails() != null && result.getDetails().getFraudPercentage() != null)
            .mapToDouble(result -> result.getDetails().getFraudPercentage())
            .average()
            .orElse(0.0);
        
        report.append("Detection Rate: ").append(String.format("%.2f%%", detectionRate)).append("\n");
        report.append("Average Risk Score: ").append(String.format("%.2f", avgRiskScore)).append("\n");
        report.append("Average Fraud Probability: ").append(String.format("%.4f", avgFraudProb)).append("\n");
        
        // Rule Effectiveness
        Map<String, Long> ruleStats = testResults.stream()
            .filter(result -> result.getFiredAIRules() != null)
            .flatMap(result -> result.getFiredAIRules().stream())
            .collect(Collectors.groupingBy(rule -> rule, Collectors.counting()));
        
        if (!ruleStats.isEmpty()) {
            report.append("\nRule Effectiveness:\n");
            for (Map.Entry<String, Long> entry : ruleStats.entrySet()) {
                double effectiveness = totalTransactions > 0 ? (entry.getValue() * 100.0) / totalTransactions : 0;
                report.append("  ").append(entry.getKey()).append(": ")
                      .append(entry.getValue()).append(" triggers (")
                      .append(String.format("%.2f%%", effectiveness)).append(")\n");
            }
        }
        report.append("\n");
    }
    
    private void addRecommendations(StringBuilder report, List<AIRuleTestResultDTO> testResults) {
        report.append("RECOMMENDATIONS\n");
        report.append("-".repeat(40)).append("\n");
        
        long totalTransactions = testResults.size();
        long flaggedTransactions = testResults.stream()
            .filter(result -> result.getDetails() != null && 
                    result.getDetails().getFraudPercentage() != null && 
                    result.getDetails().getFraudPercentage() > 0.5)
            .count();
        
        double flaggedPercentage = totalTransactions > 0 ? (flaggedTransactions * 100.0) / totalTransactions : 0;
        
        double avgRiskScore = testResults.stream()
            .filter(result -> result.getDetails() != null && result.getDetails().getRiskScore() != null)
            .mapToDouble(result -> result.getDetails().getRiskScore())
            .average()
            .orElse(0.0);
        
        report.append("Based on the analysis of ").append(totalTransactions).append(" transactions:\n\n");
        
        // Flag rate analysis
        if (flaggedPercentage > 15) {
            report.append("• HIGH FLAG RATE ALERT: The current flag rate of ")
                  .append(String.format("%.2f%%", flaggedPercentage))
                  .append(" is above the recommended threshold of 15%. Consider reviewing rule sensitivity.\n");
        } else if (flaggedPercentage < 2) {
            report.append("• LOW FLAG RATE WARNING: The current flag rate of ")
                  .append(String.format("%.2f%%", flaggedPercentage))
                  .append(" may be too low. Consider reviewing rule effectiveness.\n");
        } else {
            report.append("• OPTIMAL FLAG RATE: The current flag rate of ")
                  .append(String.format("%.2f%%", flaggedPercentage))
                  .append(" appears to be within acceptable range.\n");
        }
        
        // Risk score analysis
        if (avgRiskScore > 70) {
            report.append("• HIGH AVERAGE RISK: The average risk score of ")
                  .append(String.format("%.2f", avgRiskScore))
                  .append(" indicates elevated fraud risk. Immediate review recommended.\n");
        } else if (avgRiskScore < 30) {
            report.append("• LOW AVERAGE RISK: The average risk score of ")
                  .append(String.format("%.2f", avgRiskScore))
                  .append(" suggests low fraud activity. Monitor for potential rule gaps.\n");
        }
        
        // General recommendations
        report.append("• CONTINUOUS MONITORING: Implement real-time monitoring for transactions with fraud probability > 0.7\n");
        report.append("• RULE OPTIMIZATION: Review and optimize rules that show low trigger rates or high false positive rates\n");
        report.append("• THRESHOLD ADJUSTMENT: Consider adjusting risk thresholds based on business requirements and fraud tolerance\n");
        report.append("• REGULAR TESTING: Conduct regular AI rule testing to ensure continued effectiveness\n\n");
    }
}