# Train model with YOUR real transaction data from database
# Upload your transaction_history.csv to Colab first

import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import joblib
import matplotlib.pyplot as plt
from sklearn.tree import _tree

# ============================================
# STEP 1: Load YOUR Real Data
# ============================================
print("=" * 50)
print("STEP 1: Loading Real Transaction Data")
print("=" * 50)

# Upload transactions.csv file in Colab (click folder icon -> upload)
df = pd.read_csv('transactions.csv')  # Change filename if needed
df = df.fillna(0)

print(f"Loaded {len(df)} transactions")
print(f"Unique rules: {df['fired_rule_name'].nunique()}")
print(f"\nRule distribution:\n{df['fired_rule_name'].value_counts()}")

# ============================================
# STEP 2: Train Model
# ============================================
print("\n" + "=" * 50)
print("STEP 2: Training Model")
print("=" * 50)

feature_columns = ['amount', 'transactionFeeAmount', 'settlementFeeAmount',
                   'transactionProcessingFee', 'settlementProcessingFee']

X = df[feature_columns]
y = df['fired_rule_name']

y_encoder = LabelEncoder()
y_encoded = y_encoder.fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

clf = DecisionTreeClassifier(max_depth=5, min_samples_split=2, min_samples_leaf=1, random_state=42)
clf.fit(X_train, y_train)

print(f"Model trained! Tree depth: {clf.get_depth()}, Leaves: {clf.get_n_leaves()}")

y_pred = clf.predict(X_test)
print(f"Accuracy: {accuracy_score(y_test, y_pred):.2%}")

# ============================================
# STEP 3: Visualize Decision Tree
# ============================================
print("\n" + "=" * 50)
print("STEP 3: Visualizing Tree")
print("=" * 50)

plt.figure(figsize=(25,15))
plot_tree(clf, feature_names=feature_columns, class_names=y_encoder.classes_, 
          filled=True, fontsize=8, max_depth=3)
plt.savefig('decision_tree.png', dpi=300, bbox_inches='tight')
plt.show()
print("✓ Tree visualization saved")

# ============================================
# STEP 4: Generate Drools Rules
# ============================================
print("\n" + "=" * 50)
print("STEP 4: Generating Drools Rules")
print("=" * 50)

def generate_drools_rules(clf, y_encoder, feature_names):
    tree_ = clf.tree_
    rules = []
    rule_counter = [0]
    
    def recurse(node, conditions):
        if tree_.feature[node] != _tree.TREE_UNDEFINED:
            name = feature_names[tree_.feature[node]]
            threshold = tree_.threshold[node]
            left_cond = conditions + [f"{name} > {threshold:.2f}"]
            right_cond = conditions + [f"{name} <= {threshold:.2f}"]
            recurse(tree_.children_left[node], right_cond)
            recurse(tree_.children_right[node], left_cond)
        else:
            if not conditions:
                return
            
            value = tree_.value[node][0]
            class_idx = value.argmax()
            rule_name = y_encoder.inverse_transform([class_idx])[0]
            conditions_str = ' , '.join(conditions)
            rule_id = f"AI_Generated_{rule_name}_{rule_counter[0]}"
            rule_counter[0] += 1

            drools_rule = f"""import net.com.fms_core.dto.message.IsoMessageDTO;

rule "{rule_id}"
when
    $t : IsoMessageDTO({conditions_str})
then
    $t.setRiskLevel("HIGH");
    $t.setFlaggedForReview(true);
    $t.setRuleFired(true);
    $t.setRuleName("{rule_name}");
    $t.setFiredRule("Generated by AI");
    $t.setRiskScore(7.0);
end
"""
            rules.append(drools_rule)
    
    recurse(0, [])
    return rules

rules = generate_drools_rules(clf, y_encoder, feature_columns)
print(f"Generated {len(rules)} Drools rules")

# ============================================
# STEP 5: Save Everything
# ============================================
print("\n" + "=" * 50)
print("STEP 5: Saving Files")
print("=" * 50)

joblib.dump({'model': clf, 'encoder': y_encoder}, 'decision_tree_model.pkl')
print("✓ Model saved to 'decision_tree_model.pkl'")

with open('generated_rules.drl', 'w') as f:
    for rule in rules:
        f.write(rule + "\n\n")
print("✓ Rules saved to 'generated_rules.drl'")

print("\n" + "=" * 50)
print("COMPLETE! Download decision_tree_model.pkl")
print("Place it in: fms_core/src/main/java/net/com/fms_core/script/rulegenerator/")
print("=" * 50)

print("\nPreview of generated rules:")
print("=" * 50)
for i, rule in enumerate(rules[:3]):
    print(rule)
    if i < 2:
        print("-" * 50)
