# future_rule_generator_incremental.py

import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
import joblib
import os

# -----------------------------
# CONFIGURATION
# -----------------------------
import sys

DB_CSV_FILE = sys.argv[1] if len(sys.argv) > 1 else "transaction_history.csv"
MODEL_FILE = "decision_tree_model.pkl"
OUTPUT_RULES_FILE = "generated_rules.drl"

# -----------------------------
# HELPER FUNCTIONS
# -----------------------------

def load_data(file_path):
    df = pd.read_csv(file_path)
    df = df.fillna(0)  # Fill missing values with 0
    return df

def preprocess_data(df):
    feature_columns = [
        'amount', 'transactionFeeAmount', 'settlementFeeAmount',
        'transactionProcessingFee', 'settlementProcessingFee'
    ]
    y = df['fired_rule_name']
    y_encoder = LabelEncoder()
    y_encoded = y_encoder.fit_transform(y)
    X = df[feature_columns]
    rule_templates = df.groupby('fired_rule_name')['rule_content'].first().to_dict()
    return X, y_encoded, y_encoder, rule_templates

def train_model(X, y):
    unique_classes = len(set(y))
    print(f"Training with {unique_classes} unique rule types")
    if unique_classes == 1:
        print("WARNING: Only one rule type found. Cannot generate conditions.")
        print("Need transactions with different rule names to learn patterns.")
    clf = DecisionTreeClassifier(max_depth=3, min_samples_split=2, min_samples_leaf=1, random_state=42)
    clf.fit(X, y)
    print(f"Tree depth: {clf.get_depth()}, Leaves: {clf.get_n_leaves()}")
    return clf

def save_model(clf, y_encoder, model_file):
    joblib.dump({'model': clf, 'encoder': y_encoder}, model_file)
    print(f"Model saved to {model_file}")

def load_model(model_file):
    if os.path.exists(model_file):
        data = joblib.load(model_file)
        print(f"Model loaded from {model_file}")
        return data['model'], data['encoder']
    return None, None

def update_model(clf, X, y_encoded):
    clf.fit(X, y_encoded)
    print("Model updated with new data")
    return clf

def generate_drools_rules(clf, y_encoder, X, rule_templates):
    from sklearn.tree import _tree
    tree_ = clf.tree_
    feature_names = list(X.columns)
    rules = []

    rule_counter = [0]
    
    def recurse(node, conditions):
        if tree_.feature[node] != _tree.TREE_UNDEFINED:
            name = feature_names[tree_.feature[node]]
            threshold = tree_.threshold[node]
            left_cond = conditions + [f"{name} > {threshold:.2f}"]
            right_cond = conditions + [f"{name} <= {threshold:.2f}"]
            recurse(tree_.children_left[node], left_cond)
            recurse(tree_.children_right[node], right_cond)
        else:
            if not conditions:
                return
                
            value = tree_.value[node][0]
            class_idx = value.argmax()
            rule_name = y_encoder.inverse_transform([class_idx])[0]
            conditions_str = ' , '.join(conditions)
            rule_id = f"AI_Generated_{rule_name}_{rule_counter[0]}"
            rule_counter[0] += 1

            drools_rule = f"""import net.com.fms_core.dto.message.IsoMessageDTO;

rule "{rule_id}"
when
    $t : IsoMessageDTO({conditions_str})
then
    $t.setRiskLevel("HIGH");
    $t.setFlaggedForReview(true);
    $t.setRuleFired(true);
    $t.setRuleName("{rule_name}");
    $t.setFiredRule("Generated by AI");
    $t.setRiskScore(7.0);
end
"""
            rules.append(drools_rule)

    recurse(0, [])
    return rules

def save_rules(rules, file_path):
    with open(file_path, 'w') as f:
        for r in rules:
            f.write(r)
            f.write("\n\n")
    print(f"Drools rules saved to {file_path}")
    return rules

# -----------------------------
# MAIN EXECUTION
# -----------------------------
if __name__ == "__main__":
    # 1. Load transaction data
    df = load_data(DB_CSV_FILE)
    
    # Check data diversity
    print(f"Total transactions: {len(df)}")
    print(f"Unique rules: {df['fired_rule_name'].nunique()}")
    print(f"Rule distribution:\n{df['fired_rule_name'].value_counts()}")

    # 2. Preprocess
    X, y_encoded, y_encoder, rule_templates = preprocess_data(df)

    # 3. Load pre-trained model or train new
    clf, loaded_encoder = load_model(MODEL_FILE)
    if clf is not None:
        print("Using pre-trained model from Colab")
        y_encoder = loaded_encoder
    else:
        print("Training new model with current data...")
        clf = train_model(X, y_encoded)

    # 4. Save model (optional - comment out if using pre-trained)
    # save_model(clf, y_encoder, MODEL_FILE)

    # 5. Generate Drools rules
    rules = generate_drools_rules(clf, y_encoder, X, rule_templates)

    # 6. Save rules to file
    save_rules(rules, OUTPUT_RULES_FILE)
    
    # 7. Output rules as JSON for Java to capture
    print("===RULES_START===")
    for rule in rules:
        print(rule)
    print("===RULES_END===")
