spring:
  application:
    name: fms_config
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:configs/,classpath:configs/{application}
  profiles:
    active: native 

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
